global_config:
  synthetic_resolution: [960, 540] # 960x540, 854x480, 768x432, 640x360, 480x270, 426x240

generator:
  base_image_width: 1920
  base_image_height: 1080
  
  piano_white_min_brightness: 150
  piano_black_max_brightness: 100
  color_variance: 10 # up to plus or minus that number to every RGB number

  # Desired width of the complete piano as a fraction of the image width.
  piano_width_min_fraction: 0.5
  piano_width_max_fraction: 2.0

  rotation_min_degrees: -25.0
  rotation_max_degrees: 25.0

  # Maximum perspective displacement as a fraction of the piano size.
  perspective_strength: 0.05

  brightness_range: [0.5, 1.5]
  contrast_range: [0.5, 1.5]

  blur_probability: 0.40
  noise_probability: 0.40

  flip_x_probability: 0.5
  flip_y_probability: 0.5

  jpeg_probability: 0.50

  # Opacity range for the texture/image overlaid on the piano.
  # The actual opacity varies spatially between these values.
  overlay_alpha_range: [0.0, 0.3]
